### ISSUE TITLE
Clarifications~

### ISSUE THREAD

**Issue by Catalylia** [AO-devgroup/Attorney-Online-Client#1]
This is long overdue, but I keep forgetting to post here. 

-Music list limit, s' far as I know, is already over 1000. (I think it was 3k, not sure, don't quote me on that.) I remember vividly trying to load a client for a server that had like...1457 songs. It worked, but it was a biiiiiiiiiiiiiiiiiiiiiiiiiiiiiiit of a wait.

-The entire zoom function might need a reformat it's cray cray. But moving speed lines are achievable with a few replaced resources, many char makers are just making their own zooms animated speedlines wise and over riding the default still shot.

-Please try and add a "log - off" or "return to server list" button. Please. Would make things so much more efficient than just loading a new client and killing the old one.

 -There are clients that support 240 chars, so it may be a simple bit more for 500 chars, but this is a completely new project unless I am mistaken Soo...atm I think server's seem to safely support only 300-Actually omit this. Future support. Duh. 

-If you want vanil char reduxes might be able to help there. I got too much AO chars wise. >..> _shot_

Most else I was talking about is already there sooo~.

**Comment by OmniTroid** [comment]
Zoom function is easy to do. Even with legacy support(unmodified char.inis will display moving speedlines as the background).

The client is already being built around the abilities to:
- return to the lobby
- change character without leaving the server
- hot-reloading(re-reading char.ini and other files without leaving the server)

And by communicating with serverD, neither music nor char limits should be a problem.

The vanilla pack definitely needs some work, though. If you could PM me some specific suggestions, that'd be great.
