### ISSUE TITLE
Server list received from master gets split

### ISSUE THREAD

**Issue by OmniTroid** [AO-devgroup/Attorney-Online-Client#6]
TCP splits the packet as it is too large. Only half of the masterlist shows up.

**Comment by oldmud0** [comment]
That is supposed to be handled by the TCP/IP stack, i.e. under the hood. TCP packet fragmentation should not have to be handled by software. Perhaps it is overrunning the 16k buffer you made.

**Comment by OmniTroid** [comment]
Fixed using caching.

**Comment by oldmud0** [comment]
I had a similar problem making an LCD monitor via the serial port. The solution was to put incomplete packets on an extra buffer which would be placed in front of the read buffer on the next set of reads.
