### ISSUE TITLE
Unicode, server-specific settings

### ISSUE THREAD

**Issue by oldmud0** [AO-devgroup/Attorney-Online-Client#7]
One of the biggest requirements for me to switch to this new client is Unicode support. I don't care if you have to fork the network protocol but it's critical to have at least UTF-8 support.

On top of that, server-specific settings would be neat. This would allow servers to bundle and push out custom characters, new emotes, and other images (UI?).

**Comment by OmniTroid** [comment]
Unicode support was added in 2.0.6, see http://tiny.cc/getao2

File transfer is not a part of the AO protocol and is not planned to be either. Look into themes for customization.

**Comment by oldmud0** [comment]
So even if you forked the protocol, you wouldn't add it? You mean to say, just keep making server players download big 500 MB character zip files every time there's a little change or modification to the character roster?

This was one of the reasons my friends stopped playing AO altogether. The limitations of AO were easy to reach: new players had to download a huge character roster, no matter how easy I made the task, and then had to instruct them on how to install them; then, when there was a change to one of the characters, I would have to make the changes incremental (i.e. download big zip file #1 first, then update it with zip #2, and then some other changes with zip #3), and then remind everyone across all time zones to download the new characters/changes.

Then on top of that, you couldn't make a transcript out of everything said in-character. The closest thing there is to it was the "replays" system, but only I (the server owner) could access that since it was just a big log of raw packets.

Yes, such a feature demands security measures. But until a decent protocol gets developed to make way for new features that make the game more convenient and accessible, my friends and I still won't be playing AO in the near future.

**Comment by OmniTroid** [comment]
On transcripts: AO2's chatlog is copyable. Right-click->select everything->copy.

If you want a file transfer protocol, nobody is preventing you from forking and implementing it.

**Comment by oldmud0** [comment]
You're right, nobody is. But time is. I'm still in high school, just waiting to be liberated into college where time management is looser and I can do projects with others rather than alone. Right now though, I can't be bothered to get my hands dirty on the code and help you out.
